### ISSUE TITLE
Fishy doesnt deploy generated schema

### ISSUE THREAD

**Issue by Corban-Dallas** [p2panda/fishy#10]
Can't publish freshly generated schema.lock using last version of fishy. Got this error:
```
Error: Could not publish schemas to node

Caused by:
    GraphQL request to node failed: 
    GQLClient Error: Look at json field for more details
    Message: data did not match any variant of untagged enum PlainValue
```
rollback to tag=v0.1.0 fixed the problem. Maybe some breaking changes happened and there is inconsistency with aquadogo 0.5.0?

**Comment by adzialocha** [comment]
Oh good find, the `p2panda-rs` dependency needs bouncing to it's latest release.

**Comment by adzialocha** [comment]
I've updated the version in https://github.com/p2panda/fishy/commit/ee7e21745288ce29d0d6f2f8558595989c46a376, can you see if it works now @Corban-Dallas? Thank you!

**Comment by Corban-Dallas** [comment]
Yeah, it works now, thanks! But I had to switch from aquadogo 0.5.0 to the its last sha in cargo.toml. It is not big problem, but feels kinda dirty
